### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by XiBotIrl** [stormdirus2/the-planeswalker#1]
Hello sorry but there is a way to reduce distance scaling in planewalker dimmension im asking bcs we wanted to nerf it a bit.

**Comment by stormdirus2** [comment]
Hello.
The dimension is created via Minecraft's own datapack system for it. 

[infinite_void.json](https://github.com/stormdirus2/the-planeswalker/blob/master/src/main/resources/data/theplaneswalker/dimension_type/infinite_void.json) is the dimension type responsible for the scaling. There's probably some way to override it via datapacks, but that would be outside my limited knowledge in that area.
