### ISSUE TITLE
Eating Glitch

### ISSUE THREAD

**Issue by fordz0** [stormdirus2/the-planeswalker#2]
I added planeswalker to my modpack and when you get experience, the food bar doesn't change at all.

**Comment by LordDecay26** [comment]
i, too, had this issue

**Comment by stormdirus2** [comment]
If I am correct, then this is a specific mod compatibility issue.

I'm not able to recreate this issue in a singleplayer world. I'll try a server soon.

If you could narrow down the conflicting mod(s), that would be great.

I know I am tackling this VERY late.

**Comment by stormdirus2** [comment]
I have not been able to recreate this issue in a multiplayer world either.

**Comment by LordDecay26** [comment]
> I added planeswalker to my modpack and when you get experience, the food bar doesn't change at all.

my modpack has 200+ mods, im not able to find the source. what mods are you playing with? if we can compare them, we can narrow the source down to whichever mods we both have installed. please reply.

**Comment by stormdirus2** [comment]
@LordDecay26 
Huh. Well, conceptually, whatever is causing the conflict must be somehow modifying how experience orbs work, how mending works, or how hunger works.

If you could isolate mods that do things like that and try to recreate the conflict with them, you might find the cause.
Then, I could maybe find a way to handle the logic so that it doesn't conflict anymore.

**Comment by stormdirus2** [comment]
Also, if you were to share the mod list, I could try to narrow it down as well.

**Comment by LordDecay26** [comment]
here is the link to my modpack,  the issue is persistent between both the BETA 1.17 updates.
https://www.curseforge.com/minecraft/modpacks/besmirchment-psm/files/3501659

just download it, then you can see the mod list and try to figure out which one is the culprit.

**Comment by stormdirus2** [comment]
@LordDecay26 I FOUND IT!

It's the Clumps mod. I believe it to be an easy patch so hold on for a tad.

I'll experiment with a solution that will not only fix this, but other potential incompatibilities of the same variety.

**Comment by LordDecay26** [comment]
> @LordDecay26 I FOUND IT!
> 
> It's the Clumps mod. I believe it to be an easy patch so hold on for a tad.
> 
> I'll experiment with a solution that will not only fix this, but other potential incompatibilities of the same variety.

NICE

**Comment by stormdirus2** [comment]
@LordDecay26 @pengu1ndev 

Fixed! You can grab the file early to test from here:
> https://github.com/stormdirus2/the-planeswalker/releases/tag/v2.1.1

I'll push this to CurseForge.
